export const compareTours = [
  {
    id: 1,
    title: "Paris Evening Cruise",
    price: "$75",
    duration: "3 hours",
    highlights: "Evening cruise with dinner",
    availability: "Available",
    guide: "Local guide",
    transportation: "Boat",
  },
  {
    id: 2,
    title: "Louvre Museum Tour",
    price: "$65",
    duration: "4 hours",
    highlights: "Skip-the-line access, guided tour",
    availability: "Limited",
    guide: "Art historian",
    transportation: "Walking",
  },
  {
    id: 3,
    title: "Montmartre Walking Tour",
    price: "$45",
    duration: "2.5 hours",
    highlights: "Historic district, artists' square",
    availability: "Available",
    guide: "Local expert",
    transportation: "Walking",
  },
  {
    id: 4,
    title: "Versailles Palace & Gardens",
    price: "$95",
    duration: "6 hours",
    highlights: "Palace tour, gardens, round-trip transport",
    availability: "Available",
    guide: "Certified guide",
    transportation: "Air-conditioned bus",
  },
];

export const tours = [
  {
    id: 1,
    title: "Paris Evening Cruise",
    time: "6:00 PM - 9:00 PM",
    price: "$75",
    description: "Enjoy a romantic evening cruise in Paris.",
    image:
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&h=300&fit=crop",
    duration: "3 hours",
    highlights: "Evening cruise",
    availability: "Available",
    guide: "Local guide",
    transportation: "Boat",
  },
  {
    id: 2,
    title: "Paris Evening Cruise",
    time: "6:00 PM - 9:00 PM",
    price: "$75",
    description: "Enjoy a romantic evening cruise in Paris.",
    image:
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&h=300&fit=crop",
    duration: "3 hours",
    highlights: "Evening cruise",
    availability: "Available",
    guide: "Local guide",
    transportation: "Boat",
  },
  {
    id: 2,
    title: "Paris Evening Cruise",
    time: "6:00 PM - 9:00 PM",
    price: "$75",
    description: "Enjoy a romantic evening cruise in Paris.",
    image:
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&h=300&fit=crop",
    duration: "3 hours",
    highlights: "Evening cruise",
    availability: "Available",
    guide: "Local guide",
    transportation: "Boat",
  },
  {
    id: 2,
    title: "Paris Evening Cruise",
    time: "6:00 PM - 9:00 PM",
    price: "$75",
    description: "Enjoy a romantic evening cruise in Paris.",
    image:
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&h=300&fit=crop",
    duration: "3 hours",
    highlights: "Evening cruise",
    availability: "Available",
    guide: "Local guide",
    transportation: "Boat",
  },
];
