import type { LocationOption, Flight } from "@/types/flight";
import type { Place } from "../types/map";

export const LOCATIONS: LocationOption[] = [
  { id: "1", name: "Cairo", country: "Egypt" },
  { id: "2", name: "Tokyo", country: "Japan" },
  { id: "3", name: "London", country: "United Kingdom" },
  { id: "4", name: "New York", country: "USA" },
  { id: "5", name: "Paris", country: "France" },
];

export const PASSENGER_OPTIONS = [
  { value: 1, label: "1 Passenger" },
  { value: 2, label: "2 Passengers" },
  { value: 3, label: "3 Passengers" },
  { value: 4, label: "4+ Passengers" },
];

export const MOCK_FLIGHTS: Flight[] = [
  {
    id: "f1",
    departureTime: "7:05 AM",
    arrivalTime: "8:55 PM",
    originCode: "YUL",
    destinationCode: "YUL",
    duration: "18:55",
    airline: "Scoot",
    price: 1300,
    layover: { location: "YYZ", duration: "3:55" },
  },
  {
    id: "f2",
    departureTime: "9:05 AM",
    arrivalTime: "4:05 PM",
    originCode: "YUL",
    destinationCode: "YUL",
    duration: "18:55",
    airline: "Scoot",
    price: 1400,
    layover: { location: "YYZ", duration: "3:55" },
  },
  {
    id: "f3",
    departureTime: "9:05 AM",
    arrivalTime: "4:55 PM",
    originCode: "YUL",
    destinationCode: "YUL",
    duration: "18:55",
    airline: "Scoot",
    price: 1300,
    layover: { location: "YYZ", duration: "3:55" },
  },
];

export const MOCK_PLACES: Place[] = [
  // ============== RESTAURANTS ==============
  {
    id: "1",
    name: "Abou El Sid",
    category: "restaurant",
    lat: 30.0529,
    lng: 31.2465,
    rating: 4.7,
    priceLevel: "$$$",
    address: "157 26th July St, Zamalek",
  },
  {
    id: "2",
    name: "Felfela",
    category: "restaurant",
    lat: 30.0488,
    lng: 31.2434,
    rating: 4.2,
    priceLevel: "$$",
    address: "15 Hoda Shaarawy St, Downtown",
  },
  {
    id: "3",
    name: "Sequoia",
    category: "restaurant",
    lat: 30.0608,
    lng: 31.2248,
    rating: 4.5,
    priceLevel: "$$$$",
    address: "53 Abou El Feda, Zamalek",
  },
  {
    id: "4",
    name: "Kazoku",
    category: "restaurant",
    lat: 30.0567,
    lng: 31.2412,
    rating: 4.4,
    priceLevel: "$$$",
    address: "Citystars Mall, Heliopolis",
  },
  {
    id: "14",
    name: "Zooba",
    category: "restaurant",
    lat: 30.0578,
    lng: 31.2392,
    rating: 4.3,
    priceLevel: "$$",
    address: "26th of July St, Zamalek",
  },
  {
    id: "15",
    name: "Andrea",
    category: "restaurant",
    lat: 30.1158,
    lng: 31.3468,
    rating: 4.4,
    priceLevel: "$$",
    address: "Mariouteya Canal, New Cairo",
  },
  {
    id: "16",
    name: "Osmanly Restaurant",
    category: "restaurant",
    lat: 30.0492,
    lng: 31.2268,
    rating: 4.6,
    priceLevel: "$$$$",
    address: "Kempinski Nile Hotel, Garden City",
  },
  {
    id: "17",
    name: "Tabla Luna",
    category: "restaurant",
    lat: 30.0592,
    lng: 31.2214,
    rating: 4.3,
    priceLevel: "$$$",
    address: "12 Hassan Sabri, Zamalek",
  },
  {
    id: "18",
    name: "Kebabgy",
    category: "restaurant",
    lat: 30.0481,
    lng: 31.2208,
    rating: 4.2,
    priceLevel: "$$",
    address: "Cairo Marriott Hotel, Zamalek",
  },
  {
    id: "19",
    name: "Left Bank",
    category: "restaurant",
    lat: 30.0598,
    lng: 31.2194,
    rating: 4.1,
    priceLevel: "$$",
    address: "53 Abou El Feda, Zamalek",
  },
  {
    id: "20",
    name: "Pier 88",
    category: "restaurant",
    lat: 30.0614,
    lng: 31.2232,
    rating: 4.4,
    priceLevel: "$$$",
    address: "Nile City Towers, Corniche El Nil",
  },

  // ============== HOTELS ==============
  {
    id: "5",
    name: "Four Seasons Hotel Cairo at Nile Plaza",
    category: "hotel",
    lat: 30.0489,
    lng: 31.2264,
    rating: 4.9,
    priceLevel: "$$$$",
    address: "1089 Corniche El Nil, Garden City",
  },
  {
    id: "6",
    name: "Cairo Marriott Hotel",
    category: "hotel",
    lat: 30.0486,
    lng: 31.2203,
    rating: 4.6,
    priceLevel: "$$$",
    address: "16 Saray El Gezira, Zamalek",
  },
  {
    id: "7",
    name: "Kempinski Nile Hotel",
    category: "hotel",
    lat: 30.0628,
    lng: 31.2241,
    rating: 4.5,
    priceLevel: "$$$$",
    address: "12 Ahmed Ragheb, Garden City",
  },
  {
    id: "8",
    name: "Safir Hotel Cairo",
    category: "hotel",
    lat: 30.0551,
    lng: 31.2483,
    rating: 4.1,
    priceLevel: "$$",
    address: "Midan El Missaha, Dokki",
  },
  {
    id: "21",
    name: "The Nile Ritz-Carlton",
    category: "hotel",
    lat: 30.0458,
    lng: 31.2331,
    rating: 4.8,
    priceLevel: "$$$$",
    address: "1113 Corniche El Nil, Downtown",
  },
  {
    id: "22",
    name: "Fairmont Nile City",
    category: "hotel",
    lat: 30.0612,
    lng: 31.2245,
    rating: 4.7,
    priceLevel: "$$$$",
    address: "Nile City Towers, Corniche El Nil",
  },
  {
    id: "23",
    name: "Steigenberger Hotel El Tahrir",
    category: "hotel",
    lat: 30.0482,
    lng: 31.2358,
    rating: 4.3,
    priceLevel: "$$$",
    address: "Kasr El Ainy St, Downtown",
  },
  {
    id: "24",
    name: "Hilton Cairo Zamalek Residences",
    category: "hotel",
    lat: 30.0618,
    lng: 31.2189,
    rating: 4.4,
    priceLevel: "$$$$",
    address: "21 Mohamed Mazhar, Zamalek",
  },
  {
    id: "25",
    name: "Novotel Cairo Airport",
    category: "hotel",
    lat: 30.1105,
    lng: 31.3952,
    rating: 4.0,
    priceLevel: "$$",
    address: "Airport Road, Heliopolis",
  },
  {
    id: "26",
    name: "Le Méridien Pyramids Hotel",
    category: "hotel",
    lat: 29.9885,
    lng: 31.1518,
    rating: 4.3,
    priceLevel: "$$$",
    address: "El Remaya Square, Giza",
  },

  // ============== TOURIST PLACES ==============
  {
    id: "9",
    name: "The Egyptian Museum",
    category: "tourist",
    lat: 30.0478,
    lng: 31.2336,
    rating: 4.6,
    address: "Tahrir Square, Downtown",
  },
  {
    id: "10",
    name: "The Great Pyramid of Giza",
    category: "tourist",
    lat: 29.9792,
    lng: 31.1342,
    rating: 4.8,
    address: "Giza Plateau",
  },
  {
    id: "11",
    name: "Khan el-Khalili",
    category: "tourist",
    lat: 30.0475,
    lng: 31.2624,
    rating: 4.5,
    address: "Islamic Cairo",
  },
  {
    id: "12",
    name: "The Citadel of Saladin",
    category: "tourist",
    lat: 30.0295,
    lng: 31.2612,
    rating: 4.7,
    address: "Al Abageyah, El Khalifa",
  },
  {
    id: "13",
    name: "Al-Azhar Park",
    category: "tourist",
    lat: 30.0408,
    lng: 31.2681,
    rating: 4.6,
    address: "Salah Salem St, Darassa",
  },
  {
    id: "27",
    name: "The Sphinx",
    category: "tourist",
    lat: 29.9753,
    lng: 31.1376,
    rating: 4.8,
    address: "Giza Plateau, Giza",
  },
  {
    id: "28",
    name: "Coptic Cairo",
    category: "tourist",
    lat: 30.0062,
    lng: 31.2301,
    rating: 4.5,
    address: "Mar Girgis, Kom Ghorab",
  },
  {
    id: "29",
    name: "Cairo Tower",
    category: "tourist",
    lat: 30.0458,
    lng: 31.2243,
    rating: 4.3,
    address: "Zamalek, Cairo",
  },
  {
    id: "30",
    name: "Al-Muizz Street",
    category: "tourist",
    lat: 30.0498,
    lng: 31.2615,
    rating: 4.6,
    address: "Islamic Cairo",
  },
  {
    id: "31",
    name: "Giza Zoo",
    category: "tourist",
    lat: 30.0286,
    lng: 31.2173,
    rating: 3.9,
    address: "Giza Square, Giza",
  },
  {
    id: "32",
    name: "Manial Palace",
    category: "tourist",
    lat: 30.0264,
    lng: 31.2268,
    rating: 4.4,
    address: "Al-Saray St, El-Manial",
  },
  {
    id: "33",
    name: "The Hanging Church",
    category: "tourist",
    lat: 30.0065,
    lng: 31.2303,
    rating: 4.5,
    address: "Mar Girgis St, Coptic Cairo",
  },
  {
    id: "34",
    name: "Museum of Islamic Art",
    category: "tourist",
    lat: 30.0445,
    lng: 31.2489,
    rating: 4.4,
    address: "Bab El Khalq, Downtown",
  },

  // ============== HOME & APARTMENTS ==============

  {
    id: "home-2",
    name: "Zamalek Penthouse",
    category: "home",
    lat: 30.0582,
    lng: 31.2218,
    rating: 5.0,
    address: "26th July Street, Zamalek",
  },
  {
    id: "home-3",
    name: "Garden City Villa",
    category: "home",
    lat: 30.0412,
    lng: 31.2298,
    rating: 5.0,
    address: "Corniche El Nil, Garden City",
  },
  {
    id: "home-4",
    name: "Heliopolis Flat",
    category: "home",
    lat: 30.0958,
    lng: 31.3204,
    rating: 5.0,
    address: "El Hegaz Street, Heliopolis",
  },
  {
    id: "home-5",
    name: "Maadi Apartment",
    category: "home",
    lat: 29.9608,
    lng: 31.2608,
    rating: 5.0,
    address: "Road 9, Maadi",
  },
  {
    id: "home-6",
    name: "Mohandessin Residence",
    category: "home",
    lat: 30.0521,
    lng: 31.2024,
    rating: 5.0,
    address: "Gameat El Dowal Street, Mohandessin",
  },
  {
    id: "home-7",
    name: "Dokki Apartment",
    category: "home",
    lat: 30.0398,
    lng: 31.2098,
    rating: 5.0,
    address: "El Tahrir Street, Dokki",
  },
  {
    id: "home-8",
    name: "Nasr City Flat",
    category: "home",
    lat: 30.0612,
    lng: 31.3354,
    rating: 5.0,
    address: "Abbas El Akkad Street, Nasr City",
  },
  {
    id: "home-9",
    name: "New Cairo Villa",
    category: "home",
    lat: 30.0184,
    lng: 31.4258,
    rating: 5.0,
    address: "90th Street, New Cairo",
  },
  {
    id: "home-10",
    name: "6th October Apartment",
    category: "home",
    lat: 29.9684,
    lng: 30.9258,
    rating: 5.0,
    address: "Central Axis Road, 6th October City",
  },
  {
    id: "home-11",
    name: "Agouza Residence",
    category: "home",
    lat: 30.0488,
    lng: 31.2132,
    rating: 5.0,
    address: "Nile Corniche, Agouza",
  },
  {
    id: "home-12",
    name: "Manial Villa",
    category: "home",
    lat: 30.0254,
    lng: 31.2282,
    rating: 5.0,
    address: "Manial Street, El-Manial",
  },
  {
    id: "home-13",
    name: "Shoubra Apartment",
    category: "home",
    lat: 30.0784,
    lng: 31.2458,
    rating: 5.0,
    address: "Shoubra Street, Shoubra",
  },
  {
    id: "home-14",
    name: "Giza Residence",
    category: "home",
    lat: 30.0124,
    lng: 31.2084,
    rating: 5.0,
    address: "Faisal Street, Giza",
  },
  {
    id: "home-15",
    name: "Hadayek El Ahram Villa",
    category: "home",
    lat: 29.9924,
    lng: 31.1358,
    rating: 5.0,
    address: "El Ahram Street, Hadayek El Ahram",
  },
  {
    id: "home-16",
    name: "Madinty Apartment",
    category: "home",
    lat: 29.9758,
    lng: 31.3158,
    rating: 5.0,
    address: "El Teseen Street, Madinty",
  },
  {
    id: "home-17",
    name: "Rehab City Villa",
    category: "home",
    lat: 30.0858,
    lng: 31.6284,
    rating: 5.0,
    address: "90th Street, Rehab City",
  },
  {
    id: "home-18",
    name: "Sheikh Zayed Penthouse",
    category: "home",
    lat: 30.0458,
    lng: 30.9858,
    rating: 5.0,
    address: "26th of July Axis, Sheikh Zayed City",
  },
  {
    id: "home-19",
    name: "Katameya Heights",
    category: "home",
    lat: 29.9584,
    lng: 31.4158,
    rating: 5.0,
    address: "Katameya Road, Katameya",
  },
  {
    id: "home-20",
    name: "Al Mokattam Apartment",
    category: "home",
    lat: 30.0158,
    lng: 31.2758,
    rating: 5.0,
    address: "El Mokattam Hills, Mokattam",
  },
  {
    id: "home-21",
    name: "El Marg Residence",
    category: "home",
    lat: 30.1558,
    lng: 31.3458,
    rating: 5.0,
    address: "El Marg Road, El Marg",
  },
  {
    id: "home-22",
    name: "Ain Shams Flat",
    category: "home",
    lat: 30.1258,
    lng: 31.2458,
    rating: 5.0,
    address: "Khalifa El Maamon Street, Ain Shams",
  },
  {
    id: "home-23",
    name: "Mataria Residence",
    category: "home",
    lat: 30.1158,
    lng: 31.3158,
    rating: 5.0,
    address: "Mataria Street, Mataria",
  },
  {
    id: "home-24",
    name: "Abbassia Apartment",
    category: "home",
    lat: 30.0658,
    lng: 31.2758,
    rating: 5.0,
    address: "Abbassia Square, Abbassia",
  },
  {
    id: "home-25",
    name: "Roda Island Villa",
    category: "home",
    lat: 30.0184,
    lng: 31.2284,
    rating: 5.0,
    address: "Manial El Roda, Roda Island",
  },
  {
    id: "home-26",
    name: "Old Cairo Residence",
    category: "home",
    lat: 30.0058,
    lng: 31.2358,
    rating: 5.0,
    address: "Coptic Cairo Area, Old Cairo",
  },
  {
    id: "home-27",
    name: "El Sakkakini Apartment",
    category: "home",
    lat: 30.0624,
    lng: 31.2624,
    rating: 5.0,
    address: "Sakkakini Square, El Sakkakini",
  },
  {
    id: "home-28",
    name: "El Daher Flat",
    category: "home",
    lat: 30.0584,
    lng: 31.2758,
    rating: 5.0,
    address: "El Daher Street, El Daher",
  },
  {
    id: "home-29",
    name: "Boulak Residence",
    category: "home",
    lat: 30.0624,
    lng: 31.2384,
    rating: 5.0,
    address: "Boulak Abu El Ela, Boulak",
  },
  {
    id: "home-30",
    name: "El Sayeda Zeinab Apartment",
    category: "home",
    lat: 30.0358,
    lng: 31.2458,
    rating: 5.0,
    address: "El Sayeda Zeinab Square, El Sayeda Zeinab",
  },
  {
    id: "home-31",
    name: "El Khalifa Villa",
    category: "home",
    lat: 30.0284,
    lng: 31.2624,
    rating: 5.0,
    address: "El Khalifa District, El Khalifa",
  },
  {
    id: "home-32",
    name: "El Moski Residence",
    category: "home",
    lat: 30.0484,
    lng: 31.2524,
    rating: 5.0,
    address: "El Moski Street, El Moski",
  },
  {
    id: "home-33",
    name: "El Gamaleya Flat",
    category: "home",
    lat: 30.0458,
    lng: 31.2624,
    rating: 5.0,
    address: "El Gamaleya District, Islamic Cairo",
  },
  {
    id: "home-34",
    name: "El Hussein Apartment",
    category: "home",
    lat: 30.0484,
    lng: 31.2658,
    rating: 5.0,
    address: "El Hussein District, Islamic Cairo",
  },
  {
    id: "home-35",
    name: "El Azhar Residence",
    category: "home",
    lat: 30.0458,
    lng: 31.2624,
    rating: 5.0,
    address: "Near Al-Azhar Mosque, Islamic Cairo",
  },
  {
    id: "home-36",
    name: "El Darb El Ahmar Villa",
    category: "home",
    lat: 30.0384,
    lng: 31.2584,
    rating: 5.0,
    address: "El Darb El Ahmar District, Islamic Cairo",
  },
  {
    id: "home-37",
    name: "Bab El Louk Apartment",
    category: "home",
    lat: 30.0458,
    lng: 31.2384,
    rating: 5.0,
    address: "Bab El Louk Square, Bab El Louk",
  },
  {
    id: "home-38",
    name: "Kasr El Nil Residence",
    category: "home",
    lat: 30.0484,
    lng: 31.2358,
    rating: 5.0,
    address: "Kasr El Nil Street, Downtown",
  },
  {
    id: "home-39",
    name: "El Gezira Villa",
    category: "home",
    lat: 30.0458,
    lng: 31.2258,
    rating: 5.0,
    address: "El Gezira Island, Zamalek",
  },
  {
    id: "home-40",
    name: "El Manyal Palace Residence",
    category: "home",
    lat: 30.0258,
    lng: 31.2284,
    rating: 5.0,
    address: "El Manyal Palace Area, Manyal",
  },
  {
    id: "home-41",
    name: "El Warraq Flat",
    category: "home",
    lat: 30.1058,
    lng: 31.2258,
    rating: 5.0,
    address: "El Warraq Island, Imbaba",
  },
  {
    id: "home-42",
    name: "El Manial Apartment",
    category: "home",
    lat: 30.0258,
    lng: 31.2358,
    rating: 5.0,
    address: "El Manial District, Manyal",
  },
  {
    id: "home-43",
    name: "El Haram Residence",
    category: "home",
    lat: 29.9858,
    lng: 31.1324,
    rating: 5.0,
    address: "Pyramids Road, El Haram",
  },
  {
    id: "home-44",
    name: "El Omraniya Villa",
    category: "home",
    lat: 30.0658,
    lng: 31.1858,
    rating: 5.0,
    address: "El Omraniya District, Giza",
  },
  {
    id: "home-45",
    name: "El Badrasheen Apartment",
    category: "home",
    lat: 29.9358,
    lng: 31.2524,
    rating: 5.0,
    address: "El Badrasheen District, Giza",
  },
  {
    id: "home-46",
    name: "El Saff Residence",
    category: "home",
    lat: 29.5658,
    lng: 31.2858,
    rating: 5.0,
    address: "El Saff District, Giza",
  },
  {
    id: "home-47",
    name: "El Ayyat Villa",
    category: "home",
    lat: 29.6158,
    lng: 31.2658,
    rating: 5.0,
    address: "El Ayyat District, Giza",
  },
  {
    id: "home-48",
    name: "El Hawamdia Flat",
    category: "home",
    lat: 29.8958,
    lng: 31.2524,
    rating: 5.0,
    address: "El Hawamdia District, Giza",
  },
  {
    id: "home-49",
    name: "El Kerdasa Residence",
    category: "home",
    lat: 30.0558,
    lng: 31.1258,
    rating: 5.0,
    address: "El Kerdasa District, Giza",
  },
  {
    id: "home-50",
    name: "El Warraq Apartment",
    category: "home",
    lat: 30.1458,
    lng: 31.1858,
    rating: 5.0,
    address: "El Warraq District, Imbaba",
  },

  // ============== CAFES ==============
  {
    id: "35",
    name: "Cilantro",
    category: "restaurant", // Using restaurant category for cafes
    lat: 30.0584,
    lng: 31.2402,
    rating: 4.2,
    priceLevel: "$$",
    address: "Zamalek, Cairo",
  },
  {
    id: "36",
    name: "Beano's",
    category: "restaurant",
    lat: 30.0542,
    lng: 31.2458,
    rating: 4.0,
    priceLevel: "$",
    address: "26th July St, Zamalek",
  },
  {
    id: "37",
    name: "Starbucks",
    category: "restaurant",
    lat: 30.0471,
    lng: 31.2348,
    rating: 4.1,
    priceLevel: "$$",
    address: "Talaat Harb St, Downtown",
  },

  // ============== SHOPPING ==============
  {
    id: "38",
    name: "Citystars Mall",
    category: "tourist", // Using tourist category for shopping
    lat: 30.0824,
    lng: 31.3428,
    rating: 4.4,
    address: "Omar Ibn El Khattab, Heliopolis",
  },
  {
    id: "39",
    name: "Mall of Arabia",
    category: "tourist",
    lat: 29.9992,
    lng: 31.0128,
    rating: 4.3,
    address: "Juhayna Square, 6th of October City",
  },
  {
    id: "40",
    name: "Cairo Festival City",
    category: "tourist",
    lat: 30.0284,
    lng: 31.4068,
    rating: 4.5,
    address: "New Cairo",
  },
];
